In [5]:
# Dependencies and Setup
import pandas as pd
import numpy as np

In [6]:
# File to Load (Remember to Change These)
file_to_load = "./Resources/cities.csv"

In [7]:
# Read Purchasing File and store into Pandas data frame
city_data = pd.read_csv(file_to_load)

In [8]:
city_data

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,qaanaaq,77.4840,-69.3632,28.60,74,61,4.45,GL,4/25/2021 14:15
1,lavrentiya,65.5833,-171.0000,21.07,88,100,3.91,RU,4/25/2021 14:12
2,koumac,-20.5667,164.2833,75.15,85,100,11.52,NC,4/25/2021 14:15
3,buraydah,26.3260,43.9750,98.60,13,75,10.36,SA,4/25/2021 14:15
4,mahebourg,-20.4081,57.7000,78.80,78,75,13.80,MU,4/25/2021 14:15
...,...,...,...,...,...,...,...,...,...
546,santa isabel do rio negro,-0.4139,-65.0192,86.72,61,81,5.66,BR,4/25/2021 14:17
547,amapa,1.0000,-52.0000,78.62,93,98,3.18,BR,4/25/2021 14:13
548,lyndon,38.2567,-85.6016,53.60,76,90,6.91,US,4/25/2021 14:17
549,almaznyy,48.0448,40.0450,57.20,26,0,2.24,RU,4/25/2021 14:17
550,sterling,39.0062,-77.4286,55.40,76,75,12.66,US,4/25/2021 14:17

In [9]:
city_data.to_html("city_data.html", index = False, classes = ["table", "table-striped", "table-hover"])